In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.7.1
False


## Introduction to Tensors
###  Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [10]:
# scalar 
scalar = torch.tensor(7)
print(scalar)


tensor(7)


In [17]:
scalar.ndim

0

In [18]:
#Get tensor back as python int 
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [21]:
vector.ndim

1

In [22]:
vector.shape

torch.Size([2])

In [25]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
MATRIX.ndim

2

In [29]:
MATRIX[1]

tensor([ 9, 10])

In [30]:
MATRIX.shape

torch.Size([2, 2])

In [32]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they 
start with tensors full of random numbers and then adjust those 
random numbers to better represent the data.

`Start with the random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [35]:
# Create a radmon tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3358, 0.6847, 0.6001, 0.8898],
        [0.4403, 0.3606, 0.9889, 0.6475],
        [0.4684, 0.0524, 0.7438, 0.5073]])

In [38]:
# Create a random tensors with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # (color channels (RGB),height, width)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [40]:
# Create a tensors of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# Create a tensors of all ones
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32