# Learn PyTorch from https://www.learnpytorch.io/

In [112]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.7.1


## Introduction to Tensors
###  Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [113]:
# scalar 
scalar = torch.tensor(7)
print(scalar)


tensor(7)


In [114]:
scalar.ndim

0

In [115]:
#Get tensor back as python int 
scalar.item()

7

In [116]:
# Vector

vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [117]:
vector.ndim

1

In [118]:
vector.shape

torch.Size([2])

In [119]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [120]:
MATRIX.ndim

2

In [121]:
MATRIX[1]

tensor([ 9, 10])

In [122]:
MATRIX.shape

torch.Size([2, 2])

In [123]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [124]:
TENSOR.ndim

3

In [125]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they 
start with tensors full of random numbers and then adjust those 
random numbers to better represent the data.

`Start with the random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [126]:
# Create a radmon tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [127]:
# Create a random tensors with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # (color channels (RGB),height, width)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [128]:
# Create a tensors of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [129]:
# Create a tensors of all ones
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [130]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [131]:
# Use torch.arange() 
# torch.range() is deprecated

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors Data Types
**NOTE** Tensors data types is one of the 3 big errors you'll run into with PyTorch & deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

Perceptron in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [133]:
# Float 32 tensors

float_32_tensor =  torch.tensor([3.0, 6.0, 9.0], dtype=None, # What datatype is the tensors (eg float32 or float64 or float16)
                                                device=None,  # Which devices is your tensors on 
                                                requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [134]:
float_32_tensor.dtype

torch.float32

In [135]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [136]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [137]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [138]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors ( tensors attributes)

1. Tensors not right datatype - to do get datatype from a tensor use `torch.dtype`
2. Tensors not right shape - to do get shape from a tensor use `torch.shape`
3. Tensors not on the right device - to do get device from a tensor use `torch.device`


In [139]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

In [140]:
# Find out details about dtypes
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensors Operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [141]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [142]:
# Multipy by 10
tensor * 10

tensor([10, 20, 30])

In [143]:
tensor

tensor([1, 2, 3])

In [144]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [145]:
# Try out PyTorch in-build functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [146]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways to perform matrix multiplication in Neural Networks and Deep Learning :
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication must follow:
1. The **inner dimensions must match**:
* `(3,2) @ (2,3)` will work
* `(3,2) @ (3,2)` will not work
* `(2,3) @ (3,2)` will work
2. The result matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)`-> `(2,2)`
* `(3,2) @ (2,3)`-> `(3,3)`

To calculate for matrix multiplication, you can use the following website: http://matrixmultiplication.xyz/


In [147]:
# Element wise operations
print(tensor ,"*",tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [148]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [149]:
# Matrix Multiplication by hand
1 * 1 + 2 * 2 + 3  * 3

14

In [150]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 741 μs, sys: 934 μs, total: 1.68 ms
Wall time: 1.03 ms


In [151]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 110 μs, sys: 130 μs, total: 240 μs
Wall time: 153 μs


tensor(14)

### One of the most common errors in deep learning : Shape Errors

In [152]:
# Shapes for the matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the function for matrix multiplication short version of torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
(tensor_A.size(), tensor_B.size())

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of our tensors using a ** transpose**. 

A **transpose** simply switches the axis or dimensions of a given tensor. 

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix mutiplication operation works when tensor_B is transposed

print(f"Original Shapes : tensor_A {tensor_A.shape}, tensor_B {tensor_B.shape}")
print(f"New Shapes : tensor_A {tensor_A.shape} (same shape as above), tensor_B {tensor_B.T.shape}")
print(f"Result Shape : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output :\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output Shape : {output.shape}")

Original Shapes : tensor_A torch.Size([3, 2]), tensor_B torch.Size([3, 2])
New Shapes : tensor_A torch.Size([3, 2]) (same shape as above), tensor_B torch.Size([2, 3])
Result Shape : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output :

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output Shape : torch.Size([3, 3])


### Finding the min, max, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor 
x = torch.arange(1, 100, 10) 
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()


(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean - noted torch.mean() function requires a tensor of float32 datatype to work 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Find the positional of the min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the mininum value with argmin() 
# returns index of target tensor where mininum value occur
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the minimum value with argmax()
# returns index of target tensor where maximum value occur

x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* **Reshaping** - reshaps an input tensor to defined shape
* **View** - Returns a view of an input tensor of certain shape but keep the same memory as the input
* **Stacking** - Combines multiple tensors on top of each other (vstack) or side by side (hstack)
* **Squeeze** - Removes a `1` dimensions from an input tensor
* **Unsqueeze** - Adds a `1` dimension to an input tensor
* **Permute** - Returns a view of an input tensor with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensors
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add a extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped.shape, x_reshaped

(torch.Size([1, 9]), tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changes z changes x ( because a view of a tensor shares the same memory as the original input )
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensor in top each other
x_stacked = torch.stack([x, x, x, x], dim=0) # vstack for dim=0 hstack for dim=1
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze - Remove single-dimensional entries from the shape of a tensor

print(f"Previous Tensor : {x_reshaped}")
print(f"Previouse Tensor Shape : {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = torch.squeeze(x_reshaped)
print(f"Squeezed Tensor : {x_squeezed}")
print(f"Squeezed Tensor Shape : {x_squeezed.shape}")


Previous Tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previouse Tensor Shape : torch.Size([1, 9])
Squeezed Tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeezed Tensor Shape : torch.Size([9])


In [ ]:
# torch.unsqueeze - Add single-dimension to a target tensor at a specified dim
print(f"Previouse tensor : {x_squeezed}")
print(f"Shape of previous tensor : {x_squeezed.shape}")

# Add a extra dimension with unsqueeze
x_unsqueezed = torch.unsqueeze(x, dim=0)
print(f"Unsqueezed tensor : {x_unsqueezed}")
print(f"Shape of unsqueezed tensor : {x_unsqueezed.shape}")

Previouse tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Shape of previous tensor : torch.Size([9])
Unsqueezed tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape of unsqueezed tensor : torch.Size([1, 9])


In [ ]:
# torch.permute - rearrange the dimensions of a target tensor in the specified order
x_origin = torch.randn(size=(224, 224, 3)) # [height, width, color channel]

# Permute the original tensor to rerange the axis or dim order
x_permuted = x_origin.permute(2, 0, 1) # shift channel color channel 2->0, height 0->1, width 1->2
print(f"Previous shape: {x_origin.shape}")
print(f"Permuted shape: {x_permuted.shape}") # [color channel, height, width] 


Previous shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch (Tensor) is similar to indexing with NumPy (Array)

In [ ]:
# Creating the tensor
import torch

x = torch.arange(start=1, end=10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# You can also use ":" to select "all" a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values 0th and 1st dimension but only index 1 of second dimension

x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 demension but only the 1 index of value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [ ]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & Numpy arrays
NumPy is a popular python library for numerical computing and machine learning.
And because of this, PyTorch has functionality to interact with NumPy arrays.

* Data in Numpy array, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor, want in Numpy array -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to torch tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning : when converting from numpy -> pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the values of array, what will this do to tensor?
array = array + 1 
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happen to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take out of random)

In short how a neural networks learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again`

To reduce the randomness in the neural networks and PyTorch comes the concept of **random seed**.

Essentially what the random seed does is "Flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5308, 0.2336, 0.1312, 0.7669],
        [0.4453, 0.3019, 0.3757, 0.6434],
        [0.3439, 0.9611, 0.3561, 0.2330]])
tensor([[0.0628, 0.1181, 0.9967, 0.1813],
        [0.7617, 0.1501, 0.8399, 0.2613],
        [0.5917, 0.3409, 0.5343, 0.6632]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproductible tensors
import torch
# set the random seed for numpy and torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

# Check if the tensors are equal
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch object on the GPU (and making faster computations)

GPUs = faster computations on numbers, CUDA + NVIDIA hardware + PyTorch work behind the scenes to make everything run faster

### Getting a GPU
1. Easiest - Use Goolge Colab for a free GPU
2. Use your own GPU - takes a little bit of setup and requires GPU
3. Use cloud computing - GCP , AWS, Azure

### Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

For PyTorch since its capable of running compute on the GPU, MPS or CPU , its best practice to setup device agnostic code : 
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. Run on GPU if available else if MPS run on MPS else run on CPU

In [ ]:
# Count number of devices
torch.mps.device_count()

1

### Putting tensors ( and models ) on the GPU or MPS or CPU

The reason we want our tensors/models on the GPU is because using GPU results is faster computations

In [154]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print("Tensor device:", tensor.device)
print("Tensor:", tensor)

Tensor device: cpu
Tensor: tensor([1, 2, 3])


In [157]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

### Moving tensor back to the CPU


In [158]:
# If tensor is on GPU or MPS, can't transform it to NumPy
tensor_on_gpu.numpy()


TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [161]:
# To fix the GPU tensor with NumPy issue ,we can first set it to the CPU

tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])