In [42]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.7.1


## Introduction to Tensors
###  Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [43]:
# scalar 
scalar = torch.tensor(7)
print(scalar)


tensor(7)


In [44]:
scalar.ndim

0

In [45]:
#Get tensor back as python int 
scalar.item()

7

In [46]:
# Vector

vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [47]:
vector.ndim

1

In [48]:
vector.shape

torch.Size([2])

In [49]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [50]:
MATRIX.ndim

2

In [51]:
MATRIX[1]

tensor([ 9, 10])

In [52]:
MATRIX.shape

torch.Size([2, 2])

In [53]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [54]:
TENSOR.ndim

3

In [55]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they 
start with tensors full of random numbers and then adjust those 
random numbers to better represent the data.

`Start with the random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [56]:
# Create a radmon tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5848, 0.4766, 0.7701, 0.2714],
        [0.9561, 0.4023, 0.5060, 0.5162],
        [0.1254, 0.1588, 0.2306, 0.7637]])

In [57]:
# Create a random tensors with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # (color channels (RGB),height, width)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [58]:
# Create a tensors of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
# Create a tensors of all ones
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [61]:
# Use torch.arange() 
# torch.range() is deprecated

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors Data Types
**NOTE** Tensors data types is one of the 3 big errors you'll run into with PyTorch & deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

Perceptron in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [63]:
# Float 32 tensors

float_32_tensor =  torch.tensor([3.0, 6.0, 9.0], dtype=None, # What datatype is the tensors (eg float32 or float64 or float16)
                                                device=None,  # Which devices is your tensors on 
                                                requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [64]:
float_32_tensor.dtype

torch.float32

In [65]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [66]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [67]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [68]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors ( tensors attributes)

1. Tensors not right datatype - to do get datatype from a tensor use `torch.dtype`
2. Tensors not right shape - to do get shape from a tensor use `torch.shape`
3. Tensors not on the right device - to do get device from a tensor use `torch.device`


In [69]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2526, 0.3623, 0.6320, 0.3556],
        [0.2317, 0.3180, 0.3788, 0.9301],
        [0.5067, 0.1921, 0.5598, 0.4070]])

In [70]:
# Find out details about dtypes
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.2526, 0.3623, 0.6320, 0.3556],
        [0.2317, 0.3180, 0.3788, 0.9301],
        [0.5067, 0.1921, 0.5598, 0.4070]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensors Operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [71]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [72]:
# Multipy by 10
tensor * 10

tensor([10, 20, 30])

In [73]:
tensor

tensor([1, 2, 3])

In [74]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [75]:
# Try out PyTorch in-build functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [76]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways to perform matrix multiplication in Neural Networks and Deep Learning :
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication must follow:
1. The **inner dimensions must match**:
* `(3,2) @ (2,3)` will work
* `(3,2) @ (3,2)` will not work
* `(2,3) @ (3,2)` will work
2. The result matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)`-> `(2,2)`
* `(3,2) @ (2,3)`-> `(3,3)`

To calculate for matrix multiplication, you can use the following website: http://matrixmultiplication.xyz/


In [77]:
# Element wise operations
print(tensor ,"*",tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [78]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [79]:
# Matrix Multiplication by hand
1 * 1 + 2 * 2 + 3  * 3

14

In [80]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 633 μs, sys: 594 μs, total: 1.23 ms
Wall time: 784 μs


In [81]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 104 μs, sys: 17 μs, total: 121 μs
Wall time: 107 μs


tensor(14)

### One of the most common errors in deep learning : Shape Errors

In [ ]:
# Shapes for the matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the function for matrix multiplication short version of torch.matmul
torch.matmul(tensor_A, tensor_B)

In [83]:
(tensor_A.size(), tensor_B.size())

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of our tensors using a ** transpose**. 

A **transpose** simply switches the axis or dimensions of a given tensor. 

In [84]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [85]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [88]:
# The matrix mutiplication operation works when tensor_B is transposed

print(f"Original Shapes : tensor_A {tensor_A.shape}, tensor_B {tensor_B.shape}")
print(f"New Shapes : tensor_A {tensor_A.shape} (same shape as above), tensor_B {tensor_B.T.shape}")
print(f"Result Shape : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output :\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output Shape : {output.shape}")

Original Shapes : tensor_A torch.Size([3, 2]), tensor_B torch.Size([3, 2])
New Shapes : tensor_A torch.Size([3, 2]) (same shape as above), tensor_B torch.Size([2, 3])
Result Shape : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output :

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output Shape : torch.Size([3, 3])
